export type BasicSize = 'sm' | 'md' | 'lg';
export type ExtendedSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type Side = 'top' | 'right' | 'bottom' | 'left';
export type Align = 'start' | 'center' | 'end';
export type CommonStylingVariant = 'default' | 'filled' | 'outline' | 'ghost';
export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
export type Tone = 'neutral' | 'accent' | 'success' | 'warning' | 'danger';
export type Emphasis = 'soft' | 'solid' | 'outline';
export type Shape = 'pill' | 'square';
export type ChoiceSize = 'md' | 'lg';
export type LabelPlacement = 'above' | 'infield';
export type CommonItemVariant = 'default' | 'destructive';
export type DialogContextValue = {
  contentRef: React.RefObject<HTMLDivElement | null>;
  overlayRef: React.RefObject<HTMLDivElement | null>;
  setContentRef: (node: HTMLDivElement | null) => void;
  setOverlayRef: (node: HTMLDivElement | null) => void;
  isExiting: () => boolean;
  requestOpen: () => void;
};
export type ForceState = 'hover' | 'active' | 'focus';
